# fly.toml app configuration file generated for car4sure-backend
app = "car4sure-backend"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

[[mounts]]
  source = "storage"
  destination = "/var/www/html/storage/app/persistent"


[deploy]
  release_command = "sh -c 'mkdir -p /var/www/html/storage/app/persistent/policies && chown -R www-data:www-data /var/www/html/storage/app/persistent && chmod -R 755 /var/www/html/storage/app/persistent && ln -sf /var/www/html/storage/app/persistent /var/www/html/public/storage'"
