# fly.toml app configuration file generated for car4sure-backend
app = "car4sure-backend"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

[[statics]]
  guest_path = "/var/www/html/public"
  url_prefix = "/"

  [[mounts]]
  source = "storage"
  destination = "/var/www/html/storage"